componentsdir = moduledir / 'components'

install_data(
    [
        '__init__.py',
    ],
    install_dir: componentsdir,
)

subdir('appearance')
subdir('battery')
subdir('bluetooth')
subdir('brightness')
subdir('datetime')
subdir('microphone')
subdir('network')
subdir('panels')
subdir('powerprofiles')
subdir('menu')
subdir('power')
subdir('speaker')
subdir('quicksettings')
