dep_gnome_desktop = dependency('gnome-desktop-4')

install_data(
    [
        '__init__.py',
        'clock.py',
        'datetime_label.py',
        'enums.py',
        'time_format_row.py',
        'timezone.py',
        'timezone_item_row.py',
        'timezone_page.py',
        'timezone_row.py',
    ],
    install_dir: componentsdir / 'datetime',
)
